# Generated by Django 4.1.1 on 2022-09-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nit', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('tipo', models.CharField(choices=[('P', 'Producto'), ('S', 'Servicios')], default='P', max_length=1)),
                ('tipo_producto', models.CharField(choices=[('E', 'Embalaje'), ('N', 'Nivel')], default='N', max_length=1)),
                ('fecha_vencimiento', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoDNiveles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidadxmedida', models.DecimalField(decimal_places=2, default=1, max_digits=9)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('salidas', models.DecimalField(decimal_places=2, max_digits=9)),
                ('entradas', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.medida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto', to='inventario.producto')),
                ('producto_nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_nivel', to='inventario.producto')),
            ],
        ),
    ]
