# Generated by Django 4.1.1 on 2022-09-09 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodniveles',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productodniveles',
            name='entradas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productodniveles',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productodniveles',
            name='producto_nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_nivel', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='productodniveles',
            name='salidas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productodniveles',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterUniqueTogether(
            name='productodniveles',
            unique_together={('producto', 'bodega', 'medida')},
        ),
    ]
