# Generated by Django 4.1.1 on 2022-09-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.medida'),
        ),
    ]
