# Generated by Django 4.1.1 on 2022-09-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_medida'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productodniveles',
            unique_together={('producto', 'bodega')},
        ),
        migrations.RemoveField(
            model_name='productodniveles',
            name='medida',
        ),
    ]
