# Generated by Django 4.1.1 on 2022-09-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_compradetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.compra'),
        ),
    ]
