# Generated by Django 4.1.1 on 2022-09-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_compra_fecha_alter_compra_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompraDetalle',
        ),
    ]
