# Generated by Django 4.1.1 on 2022-09-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_compradetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.cliente')),
            ],
        ),
    ]
