# Generated by Django 4.1.1 on 2022-09-09 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidades', models.DecimalField(decimal_places=2, max_digits=9)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('productodetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productodniveles')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.venta')),
            ],
        ),
    ]
